# Generated by Django 4.2.5 on 2023-09-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_go', '0001_add_model_film'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=20, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['id'],
            },
        ),
    ]
