# Generated by Django 4.2.5 on 2023-09-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_go', '0002_add_model_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Актер',
                'verbose_name_plural': 'Актера',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['id'], 'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильма'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['id'], 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанра'},
        ),
    ]
