# Generated by Django 4.2.5 on 2023-09-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_go', '0005_change_model_film_genre_actor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='actor',
        ),
        migrations.AddField(
            model_name='film',
            name='actor',
            field=models.ManyToManyField(to='kino_go.actor'),
        ),
    ]
