# Generated by Django 4.2.5 on 2023-09-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_go', '0007_change_model_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='lang',
            field=models.CharField(choices=[('Рус', 'Ru'), ('Нем', 'Ge'), ('Укр', 'Ua'), ('Пол', 'Pl')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.IntegerField(verbose_name='Год'),
        ),
    ]
